"""Generates src/win16/ApiCatalog.cpp: ordinal, name, calling convention,
parameter types and constant values of the Windows 3.x system DLLs.

The source is Wine's 16-bit .spec files (Wine, https://www.winehq.org/,
LGPL-2.1-or-later). Only these interface facts are taken from them; no Wine
code is used. See "Third-party code" in README.md.

    gh api repos/wine-mirror/wine/contents/dlls/user.exe16/user.exe16.spec \
        --jq .content | base64 -d > specs/user.exe16.spec
    ...
    python tools/gen_win16_catalog.py specs/ > src/win16/ApiCatalog.cpp
"""

import os
import re
import sys

# Spec file -> module name, in the order the table lists them.
MODULES = [
    ("krnl386.exe16", "KERNEL"), ("user.exe16", "USER"), ("gdi.exe16", "GDI"),
    ("keyboard.drv16", "KEYBOARD"), ("sound.drv16", "SOUND"), ("mmsystem.dll16", "MMSYSTEM"),
    ("shell.dll16", "SHELL"), ("commdlg.dll16", "COMMDLG"), ("win87em.dll16", "WIN87EM"),
    ("lzexpand.dll16", "LZEXPAND"), ("ver.dll16", "VER"), ("toolhelp.dll16", "TOOLHELP"),
    ("system.drv16", "SYSTEM"), ("ddeml.dll16", "DDEML"), ("winsock.dll16", "WINSOCK"),
    ("display.drv16", "DISPLAY"), ("mouse.drv16", "MOUSE"), ("comm.drv16", "COMM"),
    ("wing.dll16", "WING"),
]

# Parameter type -> one character (see ApiCatalog.h).
PARAMS = {"word": "w", "s_word": "s", "long": "l", "ptr": "p", "segptr": "P", "str": "z", "segstr": "Z"}

# ordinal, kind, flags, name, (parameters), rest. Wine sometimes puts a space
# before the parameter list ("Polygon (word ptr word)").
LINE = re.compile(r"^\s*(\d+)\s+(\w+)\s+((?:-\S+\s+)*)([^\s(]+)\s*(?:\(([^)]*)\))?\s*(\S*)")


def parse(path):
    entries = {}
    for raw in open(path, encoding="utf-8", errors="replace"):
        line = raw.split("#", 1)[0].rstrip()
        m = LINE.match(line)
        if not m:
            continue
        ordinal, kind, flags, name, params, rest = m.groups()
        ordinal = int(ordinal)
        flags = flags.split()
        if any(f.startswith("-arch=") and "win16" not in f for f in flags):
            continue
        if name.startswith("__wine") or name.startswith("ordinal_only"):
            continue
        entry = {"ordinal": ordinal, "name": name, "params": None, "ret16": "-ret16" in flags, "value": 0}
        if kind == "pascal":
            if "-register" in flags:
                entry["kind"] = "Register"
            else:
                entry["kind"] = "Pascal"
                types = params.split() if params is not None else None
                if types is not None and all(t in PARAMS for t in types):
                    entry["params"] = "".join(PARAMS[t] for t in types)
        elif kind == "varargs":
            entry["kind"] = "Varargs"
        elif kind == "equate":
            entry["kind"] = "Equate"
            entry["value"] = int(rest, 0) if rest else 0
        elif kind == "variable":
            entry["kind"] = "Variable"
        elif kind == "stub":
            entry["kind"] = "Stub"
        else:
            continue
        entries.setdefault(ordinal, entry)  # first definition wins
    return [entries[k] for k in sorted(entries)]


def main():
    spec_dir = sys.argv[1]
    out = sys.stdout
    out.write("// Generated by tools/gen_win16_catalog.py - do not edit.\n")
    out.write("// Ordinals, names, calling conventions, parameter types and constants of the\n")
    out.write("// Windows 3.x system DLLs.\n")
    out.write("//\n")
    out.write("// Attribution: derived from the 16-bit DLL .spec files of Wine\n")
    out.write("// (https://www.winehq.org/, LGPL-2.1-or-later). Only interface facts are\n")
    out.write("// taken; no Wine code is used. See \"Third-party code\" in README.md.\n\n")
    out.write('#include "win16/ApiCatalog.h"\n\nnamespace retro::win16 {\nnamespace {\n\n')
    out.write("using K = CatalogKind;\n\n")
    tables = []
    for spec, module in MODULES:
        path = os.path.join(spec_dir, spec + ".spec")
        entries = parse(path)
        var = "k" + module.capitalize()
        tables.append((module, var, len(entries)))
        out.write(f"constexpr CatalogEntry {var}[] = {{\n")
        for e in entries:
            params = f'"{e["params"]}"' if e["params"] is not None else "nullptr"
            ret16 = "true" if e["ret16"] else "false"
            out.write(f'    {{{e["ordinal"]}, K::{e["kind"]}, {ret16}, {e["value"]:#x}, "{e["name"]}", {params}}},\n')
        out.write("};\n\n")
    out.write("}  // namespace\n\n")
    out.write("const CatalogModule kCatalog[] = {\n")
    for module, var, count in tables:
        out.write(f'    {{"{module}", {var}, {count}}},\n')
    out.write("};\n")
    out.write("const size_t kCatalogSize = sizeof(kCatalog) / sizeof(kCatalog[0]);\n\n")
    out.write("}  // namespace retro::win16\n")


if __name__ == "__main__":
    main()
